bind = "0.0.0.0:10000"
workers = 4
worker_class = "uvicorn.workers.UvicornWorker"
timeout = 120
accesslog = "-"
errorlog = "-"
loglevel = "info"
capture_output = True
proc_name = "my_fastapi_app"
reload = True
preload_app = True
max_requests = 1000
max_requests_jitter = 50
keepalive = 5
forwarded_allow_ips = "*"
graceful_timeout = 30
threads = 2
daemon = False
enable_stdio_inheritance = True
spew = False
raw_env = [
    "ENV=production",
    "DEBUG=False",
]
default_proc_name = "my_fastapi_app:app"
worker_tmp_dir = "/dev/shm"
ssl_certfile = "/path/to/certfile.pem"
ssl_keyfile = "/path/to/keyfile.pem"
ssl_version = 2  # PROTOCOL_TLS
ssl_ciphers = "HIGH:!aNULL:!MD5"
ssl_options = 4  # OP_NO_SSLv2
ssl_prefer_server_ciphers = True
ssl_ca_certs = "/path/to/ca_certs.pem"
ssl_crlfile = "/path/to/crlfile.pem"
proxy_protocol = False
limit_request_line = 8190
limit_request_fields = 100
limit_request_field_size = 8190
raw_env = ["TZ=UTC"]
worker_connections = 1000
sendfile = True
reuse_port = True
tcp_nodelay = True
